name: Demo Workflow
on: workflow_dispatch
  push:
  pull_request:

jobs:
  run-tests:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        python-version:
          - "3.11"
    name: Test
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install depencies
        run: python -m pip install pytest .

      - name: Run tests
        run: pytest

          
      
    
    
        
