name: Demo Workflow

on: workflow_dispatch
jobs:
  run-tests:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        python-version:
          - "3.11"
    name: Test
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install depencies
        run: python -m pip install pytest 

      - name: Install Selenium
        run: pip install selenium allure-pytest

      - name: Run tests
        run: pytest --alluredir=allure-results && dir

      - name: Allure Report action from marketplace 
        uses: simple-elf/allure-report-action@master
        if: always()
        #id: allure-report
        with:
          allure_results: allure-results
          #gh_pages: gh-pages
          #allure_report: allure-report
          allure_history: allure-history
          keep_reports: 20
      # - name: Generate report
      #  run: allure generate -c allure-results -o allure-report
      
    
    
        
